name: CI/CD Pipeline for OpenCV Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup OpenCV
        run: |
          choco install opencv -y
          setx CMAKE_PREFIX_PATH "C:\\tools\\opencv\\build"
          setx OpenCV_DIR "C:\\tools\\opencv\\build"

      - name: Configure with CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -DOpenCV_DIR="C:/tools/opencv/build/x64/vc16/lib"

      - name: Build project
        run: |
          cmake --build build --config Release

      - name: Run executable
        run: |
          build\\Release\\CPMULTI.exe
