name: CI/CD Pipeline for OpenCV Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer OpenCV
      - name: Setup OpenCV
        run: |
          choco install opencv -y
          echo OpenCV installed

      # Étape 3 : Configurer l'environnement
      - name: Add OpenCV to path
        run: |
          setx OpenCV_DIR "C:/opencv/build"
          setx PATH "%PATH%;C:/opencv/build/x64/vc16/bin"

      # Étape 4 : Configurer CMake
      - name: Configure with CMake
        run: |
          cmake -S . -B build -G "Visual Studio 16 2019"

      # Étape 5 : Compiler le projet
      - name: Build project
        run: |
          cmake --build build --config Release

      # Étape 6 : Exécuter l'exécutable pour vérifier le fonctionnement
      - name: Run executable
        run: |
          build\\Release\\CPMULTI.exe