name: Build and Test OpenCV Program

on:
  push:
    branches:
      - Mac-Features/MS  # This will trigger the workflow only for pushes to the 'Mac-Features/MS' branch
  pull_request:
    branches:
      - Mac-Features/MS  # This will trigger the workflow for pull requests targeting the 'Mac-Features/MS' branch
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: macos-latest # You can change this to 'macos-latest' if you want a macOS runner

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up CMake
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.18.0'

    # Step 3: Install OpenCV
    - name: Install OpenCV
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libopencv-dev

    
    # Step 4: Print the current working directory and files
    - name: Print current working directory
      run: |
        echo "Current directory:"
        pwd
        ls -la
        ls -la assets  # Check if the image exists inside the 'assets' folder
  
    
    - name: Remove CMakeCache.txt
      run: |
        rm -f build/CMakeCache.txt

    # Step 5: Build the program
    - name: Build program
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    # Step 6: Run the program
    - name: Run the program
      run: |
        cd build
        ./MyProject  # Ensure that 'main' is the name of your executable
