jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to 'macos-latest' if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.18.0'

    - name: Install OpenCV
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libopencv-dev

    - name: Clean build directory
      run: |
        rm -rf build  # This will delete the existing build directory
        mkdir -p build  # Recreate the build directory

    - name: Build program
      run: |
        cd build
        cmake ..
        make

    - name: Run the program
      run: |
        cd build
        ./main  # Make sure 'main' is the name of your executable
